### PR TITLE
Update README.md styling

### PR DESCRIPTION
**Pull request by sorja**
Fixed spacing between content and markdown ( ###_space_<title>)

### CODE REVIEW

**Comment by septillion-git** [comment]
What the!? Was there a change is markdown? Really? Damn...

Thanks for fixing it! Must say, don't like the new style but okay...

**Comment by sorja** [comment]
Hey,
yeah.
It can be reformatted if you want - there was markdown used but incorrectly

BR,
Miró

**Comment by septillion-git** [comment]
Reformat it how? The space makes it work again. 👍 

But it is a bit weird that GitHub just changed the Markdown syntax. Up until now the README was formatted just fine...

**Comment by sorja** [comment]
Hi,
I meant if you didn’t like the ‘new style’ it can be redone to use some other markdown styling I guess

And maybe GitHub doesn’t understand markdown without a space? dno

**Comment by septillion-git** [comment]
Yeah, but it used to understand Markdown without that space... Last time I edited the README GitHub showed it just fine. 

But yeah, not going to nag about a space. I'll probably forget to type it though next time I edit the README 👼 

Again, thanks for fixing!

**Comment by sorja** [comment]
No problem, least I could do after you helping me @ Arduino forum :)

— Outro

**Comment by septillion-git** [comment]
Ahh, you're outro! 😃 Thanks!

**Pull request merged**
