### PR TITLE
Initialize correctly _millisLast

### PR DESCRIPTION
**Pull request by J6B**
If you use FadeLed dynamically (create first FadeLed during code with
"new FadeLed(x)"), _millisLast should not start from 0

### CODE REVIEW

**Comment by septillion-git** [comment]
Mm, the initialization isn't really a problem. The problem is with `_millisLast += _interval;` if `millis()` is not close to 0... Although it should fix itself pretty quick but indeed with side effects (doing a lot of steps).

I'm thinking about how to fix it, but I rather not fix it with an extra bool. First because of the extra byte of data. And second, it dynamic creation isn't the problem,  it's the delayed first call to update().

 One fix would be to use the old `_millisLast = millisNow`.  But that can lead to drift. I think I rather do
```
    if(_millisNow - _millisLast > (_interval << 2){
      _millisLast = millisNow;
    }
    else{
      _millisLast += _interval;
    }
```
Aka, just increment if the current millis is less than 4 times `_interval` bigger than ` _lastMillis', otherwise, just jump to the current millis. 

But btw, this isn't your biggest concern if you make FadeLed object dynamically. I never designed it to be used dynamically (because I don't think it's very useful) so it's leaking a proper destruction. So the `_ledList` will just become full after dynamically creating `FADE_LED_MAX_LED` leds.

**Comment by J6B** [comment]
OK, you're solution is better.
I'm only creating object dynamically one time (no destruction-recreation), so I don't have problem about no destructor :-)

**Comment by septillion-git** [comment]
Thanks :) I think I'll add it in the next release. But I was working on some other changes but got sidetracked with other projects... And now I first have to fix the mess in my repo👼

Btw, why do you create an object dynamically?  Or does your program switch between pins? I might add a proper deconstruction in the future. But I think I'll switch to a linked list topology first.

Thanks for letting me know this problem and you're effort to fix it! 👍

**Comment by J6B** [comment]
I made a Sketch for Arilux al-lc01 and al-lc02, and pinouts are différents for RGB and RGBW.
so I'm doing it like this : 

```
//Create pointer table
FadeLed* _leds[4];

//and then later
  switch (model) {
    case 1:
      _leds[0] = new FadeLed(5);
      _leds[1] = new FadeLed(14);
      _leds[2] = new FadeLed(12);
      _leds[3] = new FadeLed(13);
      _numberOfLeds = 4;
      break;
    default:
      _leds[0] = new FadeLed(14);
      _leds[1] = new FadeLed(5);
      _leds[2] = new FadeLed(12);
      _numberOfLeds = 3;
      break;
  }
```
After that, those objects remains untouched (no destruct and don't create new FadeLed objects) and so, I have no problem about missing destructor.

**Pull request closed without merging**
