### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by per1234**

### CODE REVIEW

**Comment by septillion-git** [comment]
Hi,

Thanks for the corrections! Made some typos there :sweat_smile:

I had my doubts about led or LED. I used led throughout because that's the Dutch version, looks better and I kind of find it a word on its own. But I guess you're right so I'll change to LED (in comments, not in code).

Only one request, you changed 1000ms to 1000 ms. I find the latter incorrect because the unit should follow the number directly. Same for ampere, not 10 A but 10A. Can you change that so I can do a full pull?

**Comment by per1234** [comment]
SI specification is that there should be a space before the units. From http://www.bipm.org/en/publications/si-brochure/section5-3-3.html:
>a space is always used to separate the unit from the number

However, it is very common to not have the space and I find myself making that mistake frequently, It's of course up to you, as with LED/led, and I'm happy to make any changes you like, so let me know if I should make the change. I noticed a typo `scr` for the folder name instead of `src` and decided I should look over all the documentation for typos before submitting a pull request, otherwise I wouldn't bother suggesting such pedantic changes.

**Comment by septillion-git** [comment]
Hehe, seems you're right! Then I tend to break SI rules all the time in my papers 0:-) I find it very ugly/confusing and word processors (and browsers) now might break the unit onto the next line... So I think I'll like to stick to breaking SI rules xD

And yeah, `scr` vs `src` is easy to overlook :D Thanks again!

**Comment by per1234** [comment]
OK, I removed the spaces before the units and did a squash + force push to keep it to a single commit.

**Comment by septillion-git** [comment]
Thanks again! I merged it and I will release it as a minor release after running Doxygen.

**Pull request merged**
